/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import bd.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Administrador
 */
public class Bienvenidas extends javax.swing.JFrame {

    private PantallaOperaciones operaciones;

    public Bienvenidas() {
        initComponents();
        initVentana();
        initBD();
    }

    private void initVentana() {
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy");
        lblFecha.setText(hoy.format(formato));
        LocalTime hora = LocalTime.now();
        DateTimeFormatter formato1 = DateTimeFormatter.ofPattern("HH:mm:ss");
        String sHora = hora.format(formato1);
        lblHora.setText(sHora);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime hora = LocalTime.now();
                DateTimeFormatter formato2 = DateTimeFormatter.ofPattern("HH:mm:ss");
                String sHora = hora.format(formato2);
                lblHora.setText(sHora);
            }
        });
        timer.start();
    }

    private boolean esNumero(String s1) {
        for (int i = 0; i < s1.length(); i++) {
            if (Character.isDigit(s1.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    private void initBD() {

        conexion = Conexion.mySQL("bdproyectocajero", "root", "");
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error, no se pudo conectar a la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTeclado = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        panTarjetas = new javax.swing.JPanel();
        lblTarjeta = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        lblPin = new javax.swing.JLabel();
        txfPin = new javax.swing.JTextField();
        lblCambioIdioma = new javax.swing.JLabel();
        lblTextoBienvenida1 = new javax.swing.JLabel();
        panSuperior = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        cmbIdioma = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panTeclado.setLayout(new java.awt.GridLayout(4, 0));

        btn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/one.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        panTeclado.add(btn1);

        btn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/two.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        panTeclado.add(btn2);

        btn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/three.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panTeclado.add(btn3);

        btn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/four.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panTeclado.add(btn4);

        btn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/five.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        panTeclado.add(btn5);

        btn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/six.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        panTeclado.add(btn6);

        btn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seven.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        panTeclado.add(btn7);

        btn8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eight.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        panTeclado.add(btn8);

        btn9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nine.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        panTeclado.add(btn9);

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        panTeclado.add(btnBorrar);

        btn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zero.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        panTeclado.add(btn0);

        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter.png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        panTeclado.add(btnConfirmar);

        getContentPane().add(panTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 293, 412, 320));

        panTarjetas.setLayout(new java.awt.GridLayout(2, 0));

        lblTarjeta.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblTarjeta.setText("Introduzca su tarjeta:");
        panTarjetas.add(lblTarjeta);

        txfID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txfID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panTarjetas.add(txfID);

        lblPin.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblPin.setText("Intruduzca su pin:");
        panTarjetas.add(lblPin);

        txfPin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txfPin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panTarjetas.add(txfPin);

        getContentPane().add(panTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 205, 547, -1));

        lblCambioIdioma.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblCambioIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCambioIdioma.setText("Si su idioma nativo no es el Español, cámbielo en la parte superior derecha");
        getContentPane().add(lblCambioIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, 805, 38));

        lblTextoBienvenida1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblTextoBienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoBienvenida1.setText("Bienvenido al banco galileo, siga los pasos que se le piden debajo");
        getContentPane().add(lblTextoBienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 805, 38));

        panSuperior.setLayout(new java.awt.GridLayout());

        lblHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panSuperior.add(lblHora);

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panSuperior.add(lblFecha);

        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomaActionPerformed(evt);
            }
        });
        panSuperior.add(cmbIdioma);

        getContentPane().add(panSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 805, 34));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -7, 830, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txfPin.setText(txfPin.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txfPin.setText(txfPin.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txfPin.setText(txfPin.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txfPin.setText(txfPin.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txfPin.setText(txfPin.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txfPin.setText(txfPin.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txfPin.setText(txfPin.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txfPin.setText(txfPin.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txfPin.setText(txfPin.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txfPin.setText(txfPin.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txfPin.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        try {
            Cliente c = null;
            Tarjeta t = null;
            String sPin = txfPin.getText();
            String sID = txfID.getText();
            if (esNumero(sID) == false || esNumero(sPin) == false) {
                JOptionPane.showMessageDialog(this, "Solo se pueden escribir numeros", "ERROR", JOptionPane.ERROR_MESSAGE);
                txfID.setText("");
                txfPin.setText("");
            } else {
                sentencia = conexion.createStatement();
                String sql = "SELECT * FROM tarjetas WHERE pin=" + sPin + " and propietario=" + sID + ";";
                resultado = sentencia.executeQuery(sql);
                if (resultado.next()) {
                    int numtarjeta, propietario, pin;
                    double saldo;
                    //DATOS DE LA TARJETA
                    numtarjeta = resultado.getInt("numero");
                    propietario = resultado.getInt("propietario");
                    pin = resultado.getInt("pin");
                    saldo = resultado.getDouble("saldo");
                    t = new Tarjeta(numtarjeta, propietario, pin, saldo);
                    //DATOS DE LA CUENTA
                    sentencia1 = conexion.createStatement();
                    String sql1 = "SELECT * FROM clientes WHERE id=" + sID + ";";
                    resultado1 = sentencia1.executeQuery(sql1);
                    if (resultado1.next()) {
                        int id, tarjeta;
                        String iban, nombre, direccion;
                        id = resultado1.getInt("id");
                        tarjeta = resultado1.getInt("numtarjeta");
                        iban = resultado1.getString("IBAN");
                        nombre = resultado1.getString("nombre");
                        direccion = resultado1.getString("direccion");
                        c = new Cliente(id, tarjeta, iban, nombre, direccion);
                    }
                    if (operaciones != null) {
                        operaciones.setVisible(true);
                        this.dispose();
                    } else {
                        operaciones = new PantallaOperaciones(t, c);
                        operaciones.setVisible(true);
                        this.dispose();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No hay ninguna tarjeta registrada con este pin o ID", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Bienvenidas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        String idioma= String.valueOf(cmbIdioma.getSelectedItem());
        
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    private void cambiarIdioma(String nombreIdioma){
        Idioma idioma = new Idioma(nombreIdioma);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCambioIdioma;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTextoBienvenida1;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JPanel panTarjetas;
    private javax.swing.JPanel panTeclado;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfPin;
    // End of variables declaration//GEN-END:variables
    Connection conexion;
    Statement sentencia;
    ResultSet resultado;
    Statement sentencia1;
    ResultSet resultado1;
}
