/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import bd.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alumnoT
 */
public class PantallaOperaciones extends javax.swing.JFrame {

    private Tarjeta t;
    private Cliente c;
    private Ingresar ingreso;
    private Retirar retiro;
    private PIN cambio;
    private CuentaStatus estado;
    private Transferencia transferencia;
    private Bienvenidas bienvenido;

    public PantallaOperaciones(Tarjeta tarjeta, Cliente cliente) {
        initComponents();
        this.t = tarjeta;
        this.c = cliente;
        initVentana();
        initBD();

    }

    private PantallaOperaciones() {
        throw new UnsupportedOperationException("Debes iniciar sesion primero");
    }

    private boolean esNumero(String s1) {
        for (int i = 0; i < s1.length(); i++) {
            if (Character.isDigit(s1.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    private void initVentana() {
        System.out.println(t);
        System.out.println(c);
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE dd/MM/yyyy");
        lblFecha.setText(hoy.format(formato));
        LocalTime hora = LocalTime.now();
        DateTimeFormatter formato1 = DateTimeFormatter.ofPattern("HH:mm:ss");
        String sHora = hora.format(formato1);
        lblHora.setText(sHora);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalTime hora = LocalTime.now();
                DateTimeFormatter formato2 = DateTimeFormatter.ofPattern("HH:mm:ss");
                String sHora = hora.format(formato2);
                lblHora.setText(sHora);
            }
        });
        timer.start();
    }

    private void initBD() {

        conexion = Conexion.mySQL("bdproyectocajero", "root", "");
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error, no se pudo conectar a la base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acciones = new javax.swing.JPanel();
        btnPanIngresar = new javax.swing.JButton();
        btnPanRetirar = new javax.swing.JButton();
        btnPanTransferencia = new javax.swing.JButton();
        btnPanCambiarPin = new javax.swing.JButton();
        btnPanStatus = new javax.swing.JButton();
        btnPanSalir = new javax.swing.JButton();
        panSuperior = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panTeclado = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 720));
        setResizable(false);

        acciones.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btnPanIngresar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanIngresar.setText("Ingresar");
        btnPanIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanIngresarActionPerformed(evt);
            }
        });
        acciones.add(btnPanIngresar);

        btnPanRetirar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanRetirar.setText("Retirar");
        btnPanRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanRetirarActionPerformed(evt);
            }
        });
        acciones.add(btnPanRetirar);

        btnPanTransferencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanTransferencia.setText("Transferencia");
        btnPanTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanTransferenciaActionPerformed(evt);
            }
        });
        acciones.add(btnPanTransferencia);

        btnPanCambiarPin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanCambiarPin.setText("Cambiar PIN");
        btnPanCambiarPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanCambiarPinActionPerformed(evt);
            }
        });
        acciones.add(btnPanCambiarPin);

        btnPanStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanStatus.setText("Estado de cuenta");
        btnPanStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanStatusActionPerformed(evt);
            }
        });
        acciones.add(btnPanStatus);

        btnPanSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPanSalir.setText("Salir");
        btnPanSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanSalirActionPerformed(evt);
            }
        });
        acciones.add(btnPanSalir);

        panSuperior.setLayout(new java.awt.GridLayout());

        lblHora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panSuperior.add(lblHora);

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panSuperior.add(lblFecha);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panSuperior.add(jComboBox1);

        panTeclado.setLayout(new java.awt.GridLayout(4, 0));

        btn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/one.png"))); // NOI18N
        panTeclado.add(btn1);

        btn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/two.png"))); // NOI18N
        panTeclado.add(btn2);

        btn3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/three.png"))); // NOI18N
        panTeclado.add(btn3);

        btn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/four.png"))); // NOI18N
        panTeclado.add(btn4);

        btn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/five.png"))); // NOI18N
        panTeclado.add(btn5);

        btn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/six.png"))); // NOI18N
        panTeclado.add(btn6);

        btn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seven.png"))); // NOI18N
        panTeclado.add(btn7);

        btn8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eight.png"))); // NOI18N
        panTeclado.add(btn8);

        btn9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nine.png"))); // NOI18N
        panTeclado.add(btn9);

        btnBorrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        panTeclado.add(btnBorrar);

        btn0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zero.png"))); // NOI18N
        panTeclado.add(btn0);

        btnConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter.png"))); // NOI18N
        panTeclado.add(btnConfirmar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(panTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(621, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(panTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanSalirActionPerformed
        if (bienvenido != null) {
            bienvenido.setVisible(true);
            this.dispose();
        } else {
            bienvenido = new Bienvenidas();
            bienvenido.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPanSalirActionPerformed

    private void btnPanStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanStatusActionPerformed
        if (estado != null) {
            estado.setVisible(true);
            this.dispose();
        } else {
            estado = new CuentaStatus();
            estado.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPanStatusActionPerformed

    private void btnPanCambiarPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanCambiarPinActionPerformed
        if (cambio != null) {
            cambio.setVisible(true);
            this.dispose();
        } else {
            cambio = new PIN();
            cambio.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPanCambiarPinActionPerformed

    private void btnPanTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanTransferenciaActionPerformed
        if (transferencia != null) {
            transferencia.setVisible(true);
            this.dispose();
        } else {
            transferencia = new Transferencia();
            transferencia.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPanTransferenciaActionPerformed

    private void btnPanRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanRetirarActionPerformed
        if (retiro != null) {
            retiro.setVisible(true);
            this.dispose();
        } else {
            retiro = new Retirar();
            retiro.setVisible(true);
            this.dispose();
        }
        /*
        try {
            sentencia = conexion.createStatement();
            String sql1 = "SELECT propietario FROM tarjetas WHERE pin=" + txfPin.getText() + ";";
            resultado = sentencia.executeQuery(sql1);
            if (resultado.next()) {
                sentencia2 = conexion.createStatement();
                String sql2 = "SELECT nombre FROM clientes WHERE id=" + resultado.getString("propietario") + ";";
                resultado2 = sentencia2.executeQuery(sql2);
                if (resultado2.next()) {
                    RetiroCliente.setText(resultado2.getString("nombre"));
                }
            }
            PantallaOperaciones.setSelectedIndex(3);

        } catch (SQLException ex) {
        }
         */
    }//GEN-LAST:event_btnPanRetirarActionPerformed

    private void btnPanIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanIngresarActionPerformed
        if (ingreso != null) {
            ingreso.setVisible(true);
            this.dispose();
        } else {
            ingreso = new Ingresar();
            ingreso.setVisible(true);
            this.dispose();
        }
        /*
        try {
            sentencia = conexion.createStatement();
            String sql1 = "SELECT propietario FROM tarjetas WHERE pin=" + txfPin.getText() + ";";
            resultado = sentencia.executeQuery(sql1);
            if (resultado.next()) {
                sentencia2 = conexion.createStatement();
                String sql2 = "SELECT nombre FROM clientes WHERE id=" + resultado.getString("propietario") + ";";
                resultado2 = sentencia2.executeQuery(sql2);
                if (resultado2.next()) {
                    IngresoCliente.setText(resultado2.getString("nombre"));
                }
            }
            PantallaOperaciones.setSelectedIndex(2);

        } catch (SQLException ex) {
            Logger.getLogger(main1.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
    }//GEN-LAST:event_btnPanIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acciones;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnPanCambiarPin;
    private javax.swing.JButton btnPanIngresar;
    private javax.swing.JButton btnPanRetirar;
    private javax.swing.JButton btnPanSalir;
    private javax.swing.JButton btnPanStatus;
    private javax.swing.JButton btnPanTransferencia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JPanel panSuperior;
    private javax.swing.JPanel panTeclado;
    // End of variables declaration//GEN-END:variables
    Connection conexion;
    Statement sentencia;
    Statement sentencia2;
    ResultSet resultado;
    ResultSet resultado2;
    Tarjeta tarjeta;
    Cliente cliente;
}
